import { NextRequest } from "next/server";
import { requireConsoleSession, consoleJson } from "@/lib/console-auth";
import { supaDelete, supaGet, supaPatch } from "@/lib/supabase";
import { formatZodError } from "@/lib/console-schemas";
import { unitIdSchema, unitPatchSchema, validationError } from "../../items/_lib";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
type Context = { params: Promise<{ id: string }> };
async function visible(id: string, businessId: string) { return supaGet("units", { id: `eq.${id}`, or: `(business_id.is.null,business_id.eq.${businessId})`, select: "id,business_id,code,name,symbol,decimal_places,is_system,is_active,created_at,updated_at", limit: 1 }); }
async function owned(id: string, businessId: string) { return supaGet("units", { id: `eq.${id}`, business_id: `eq.${businessId}`, is_system: "eq.false", select: "id,business_id,code,name,symbol,decimal_places,is_system,is_active,created_at,updated_at", limit: 1 }); }
export async function GET(request: NextRequest, { params }: Context) { try { const gate = await requireConsoleSession(request); if (!gate.ok) return gate.error; const id = (await params).id; if (!unitIdSchema.safeParse(id).success) return consoleJson({ error: "Invalid unit id" }, 400); const rows = await visible(id, gate.clientId!); return rows?.[0] ? consoleJson({ unit: rows[0] }) : consoleJson({ error: "Unit not found" }, 404); } catch (e: any) { return consoleJson({ error: String(e?.message ?? e) }, 500); } }
export async function PATCH(request: NextRequest, { params }: Context) { try { let body: any; try { body = await request.json(); } catch { return consoleJson({ error: "Invalid JSON" }, 400); } const gate = await requireConsoleSession(request, body?.client_id); if (!gate.ok) return gate.error; const id = (await params).id; if (!unitIdSchema.safeParse(id).success) return consoleJson({ error: "Invalid unit id" }, 400); const rows = await owned(id, gate.clientId!); if (!rows?.[0]) return consoleJson({ error: "Unit not found or is a system unit" }, 404); const parsed = unitPatchSchema.safeParse(body); if (!parsed.success) return validationError(parsed.error); const updated = await supaPatch("units", { id: `eq.${id}`, business_id: `eq.${gate.clientId}` }, parsed.data); const unit = Array.isArray(updated) ? updated[0] : updated; return unit ? consoleJson({ unit }) : consoleJson({ error: "Unit not found" }, 404); } catch (e: any) { return consoleJson({ error: String(e?.message ?? e) }, 500); } }
export async function DELETE(request: NextRequest, { params }: Context) { try { const gate = await requireConsoleSession(request); if (!gate.ok) return gate.error; const id = (await params).id; if (!unitIdSchema.safeParse(id).success) return consoleJson({ error: "Invalid unit id" }, 400); const rows = await owned(id, gate.clientId!); if (!rows?.[0]) return consoleJson({ error: "Unit not found or is a system unit" }, 404); const deleted = await supaDelete("units", { id: `eq.${id}`, business_id: `eq.${gate.clientId}` }); return deleted?.length ? consoleJson({ ok: true }) : consoleJson({ error: "Unit not found" }, 404); } catch (e: any) { return consoleJson({ error: String(e?.message ?? e) }, 500); } }
